// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: knobCircle

#include "../ui.h"

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_mainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button1 = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_button1, 135);
    lv_obj_set_height(ui_button1, 135);
    lv_obj_set_x(ui_button1, 50);
    lv_obj_set_y(ui_button1, 20);
    lv_obj_add_flag(ui_button1, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_button1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_button1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button1, lv_color_hex(0x3399FF), LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_button1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button1, 150, LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_button1, &ui_img_932150510, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_button1,&ui_img_1704086984, LV_STATE_CHECKED);

    ui_button2 = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_button2, 135);
    lv_obj_set_height(ui_button2, 135);
    lv_obj_set_x(ui_button2, -50);
    lv_obj_set_y(ui_button2, 20);
    lv_obj_set_align(ui_button2, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_button2, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_button2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_button2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button2, lv_color_hex(0x3399FF), LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_button2, 150, LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_button2, &ui_img_932150510, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_button2, &ui_img_1704086984, LV_STATE_CHECKED);

    ui_button3 = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_button3, 135);
    lv_obj_set_height(ui_button3, 135);
    lv_obj_set_x(ui_button3, 50);
    lv_obj_set_y(ui_button3, -20);
    lv_obj_set_align(ui_button3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_button3, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_button3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_button3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button3, lv_color_hex(0x3399FF), LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_button3, 150, LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_button3, &ui_img_554538158, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button4 = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_button4, 135);
    lv_obj_set_height(ui_button4, 135);
    lv_obj_set_x(ui_button4, -50);
    lv_obj_set_y(ui_button4, -20);
    lv_obj_set_align(ui_button4, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_button4, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_button4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_button4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button4, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button4, lv_color_hex(0x3399FF), LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_button4, 150, LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_button4, &ui_img_ac_white_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resetWifi = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_resetWifi, 50);
    lv_obj_set_height(ui_resetWifi, 50);
    lv_obj_set_x(ui_resetWifi, 0);
    lv_obj_set_y(ui_resetWifi, 100);
    lv_obj_set_align(ui_resetWifi, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_resetWifi, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_resetWifi, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_resetWifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_resetWifi, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_resetWifi, lv_color_hex(0x3399FF), LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_resetWifi, 150, LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_resetWifi, &ui_img_1968931049, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Notify = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_Notify, 308);
    lv_obj_set_height(ui_Notify, 204);
    lv_obj_set_align(ui_Notify, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Notify, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Notify, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Notify, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Notify, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Notify, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Notify, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deleteNotify = lv_label_create(ui_Notify);
    lv_obj_set_width(ui_deleteNotify, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deleteNotify, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_deleteNotify, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deleteNotify, "   Device just \ngot delete from HC.");
    lv_obj_set_style_text_font(ui_deleteNotify, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mqttNotify = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_mqttNotify, 308);
    lv_obj_set_height(ui_mqttNotify, 204);
    lv_obj_set_align(ui_mqttNotify, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mqttNotify, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_mqttNotify, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_mqttNotify, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mqttNotify, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mqttNotify, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_mqttNotify, 4, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_mqttText = lv_label_create(ui_mqttNotify);
    lv_obj_set_width(ui_mqttText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mqttText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mqttText, 0);
    lv_obj_set_y(ui_mqttText, -30);
    lv_obj_set_align(ui_mqttText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mqttText, "Can't connect to \n			 HC MQTT");
    lv_obj_set_style_text_font(ui_mqttText, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ok = lv_btn_create(ui_mqttNotify);
    lv_obj_set_width(ui_ok, 100);
    lv_obj_set_height(ui_ok, 50);
    lv_obj_set_x(ui_ok, 0);
    lv_obj_set_y(ui_ok, 50);
    lv_obj_set_align(ui_ok, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ok, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ok, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ok, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ok, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ok, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ok, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ok, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_okText = lv_label_create(ui_ok);
    lv_obj_set_width(ui_okText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_okText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_okText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_okText, "OK");
    lv_obj_set_style_text_font(ui_okText, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sceneSetting = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_sceneSetting, 50);
    lv_obj_set_height(ui_sceneSetting, 50);
    lv_obj_set_x(ui_sceneSetting, 0);
    lv_obj_set_y(ui_sceneSetting, 20);
    lv_obj_set_align(ui_sceneSetting, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sceneSetting, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_sceneSetting, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sceneSetting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sceneSetting, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sceneSetting, &ui_img_1772094659, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_resetWifi, ui_event_resetWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button1, ui_event_button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button2, ui_event_button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button3, ui_event_button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button4, ui_event_button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ok, ui_event_ok, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sceneSetting, ui_event_sceneSetting, LV_EVENT_ALL, NULL);

}
