// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: knobCircle

#include "../ui.h"

void ui_SettingScreen_screen_init(void)
{
ui_SettingScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_SettingScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scene1 = lv_btn_create(ui_SettingScreen);
lv_obj_set_width( ui_scene1, 135);
lv_obj_set_height( ui_scene1, 135);
lv_obj_set_x( ui_scene1, 50 );
lv_obj_set_y( ui_scene1, 20 );
lv_obj_add_flag( ui_scene1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_scene1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_scene1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scene1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scene1, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_canh1 = lv_label_create(ui_scene1);
lv_obj_set_width( ui_canh1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canh1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_canh1, LV_ALIGN_CENTER );
lv_label_set_text(ui_canh1,"Canh 1");

ui_scene2 = lv_btn_create(ui_SettingScreen);
lv_obj_set_width( ui_scene2, 135);
lv_obj_set_height( ui_scene2, 135);
lv_obj_set_x( ui_scene2, -50 );
lv_obj_set_y( ui_scene2, 20 );
lv_obj_set_align( ui_scene2, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_scene2, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_scene2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_scene2, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scene2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scene2, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_canh2 = lv_label_create(ui_scene2);
lv_obj_set_width( ui_canh2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canh2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_canh2, LV_ALIGN_CENTER );
lv_label_set_text(ui_canh2,"Canh 2");

ui_scene3 = lv_btn_create(ui_SettingScreen);
lv_obj_set_width( ui_scene3, 135);
lv_obj_set_height( ui_scene3, 135);
lv_obj_set_x( ui_scene3, 50 );
lv_obj_set_y( ui_scene3, -20 );
lv_obj_set_align( ui_scene3, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_scene3, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_scene3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_scene3, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scene3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scene3, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_canh3 = lv_label_create(ui_scene3);
lv_obj_set_width( ui_canh3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canh3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_canh3, LV_ALIGN_CENTER );
lv_label_set_text(ui_canh3,"Canh 3");

ui_scene4 = lv_btn_create(ui_SettingScreen);
lv_obj_set_width( ui_scene4, 135);
lv_obj_set_height( ui_scene4, 135);
lv_obj_set_x( ui_scene4, -50 );
lv_obj_set_y( ui_scene4, -20 );
lv_obj_set_align( ui_scene4, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_scene4, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_scene4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_scene4, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scene4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scene4, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_canh4 = lv_label_create(ui_scene4);
lv_obj_set_width( ui_canh4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canh4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_canh4, LV_ALIGN_CENTER );
lv_label_set_text(ui_canh4,"Canh 4");

ui_back = lv_btn_create(ui_SettingScreen);
lv_obj_set_width( ui_back, 50);
lv_obj_set_height( ui_back, 50);
lv_obj_set_x( ui_back, 0 );
lv_obj_set_y( ui_back, 20 );
lv_obj_set_align( ui_back, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_back, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_back, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_back, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_back, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_back, &ui_img_1592976543, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_add_event_cb(ui_back, ui_event_back, LV_EVENT_ALL, NULL);

}
