// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: wt32sc01

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_lockScreen
void ui_lockScreen_screen_init(void);
void ui_event_lockScreen(lv_event_t * e);
lv_obj_t * ui_lockScreen;
lv_obj_t * ui_Label2;

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen(lv_event_t * e);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_lightBtnOne;
lv_obj_t * ui_Image5;
lv_obj_t * ui_lightBtnTwo;
lv_obj_t * ui_Image2;
lv_obj_t * ui_curtainBtn;
lv_obj_t * ui_Image3;
lv_obj_t * ui_acBtn;
lv_obj_t * ui_Image4;

// SCREEN: ui_secondScreen
void ui_secondScreen_screen_init(void);
void ui_event_secondScreen(lv_event_t * e);
lv_obj_t * ui_secondScreen;
lv_obj_t * ui_function1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_function2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_function3;
lv_obj_t * ui_Label5;
lv_obj_t * ui_function4;
lv_obj_t * ui_Label6;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_30409_treecanopy_v1_[1] = {&ui_img_30409_treecanopy_v1_920485_png};
const lv_img_dsc_t * ui_imgset_2039529013[1] = {&ui_img_1862871016};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_lockScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0);
    }
}
void ui_event_MainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_secondScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 150, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_secondScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 150, 0);
    }
}
void ui_event_secondScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 150, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 150, 0);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_lockScreen_screen_init();
    ui_MainScreen_screen_init();
    ui_secondScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_lockScreen);
}
