// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: knobCircle

#ifndef _KNOBCIRCLE_UI_H
#define _KNOBCIRCLE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_lumiScreen
void ui_lumiScreen_screen_init(void);
void ui_event_lumiScreen(lv_event_t * e);
extern lv_obj_t * ui_lumiScreen;
extern lv_obj_t * ui_Image1;
// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
void ui_event_button1(lv_event_t * e);
void ui_event_button2(lv_event_t * e);
void ui_event_button3(lv_event_t * e);
void ui_event_button4(lv_event_t * e);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_button1;
extern lv_obj_t * ui_button2;
extern lv_obj_t * ui_button3;
extern lv_obj_t * ui_button4;
void ui_event_resetWifi(lv_event_t * e);
extern lv_obj_t * ui_resetWifi;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_lumi_png);    // assets\lumi.png
LV_IMG_DECLARE(ui_img_932150510);    // assets\light-bulb (1).png
LV_IMG_DECLARE(ui_img_554538158);    // assets\curtains (2).png
LV_IMG_DECLARE(ui_img_ac_white_png);    // assets\AC_white.png
LV_IMG_DECLARE(ui_img_1968931049);    // assets\wifi (1).png
LV_IMG_DECLARE(ui_img_1704086984);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
